version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    image : projectlogin-golang
  db:
    image: mysql
    restart: always
    container_name: godockerDB
    environment:
      MYSQL_DATABASE: 'kp_jwt'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'toor'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: